### ISSUE TITLE
Batch Edit Permissions Does not work

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1014]
From what I can tell the edit form gets and ID associated with the item it is going to batch edit for permission editing.  This id is only valid in one of the objects and not the other object.  This causes the batch edit to fail with:
```
NoMethodError - undefined method `update' for nil:NilClass:
  hydra-access-controls (10.5.0) app/models/hydra/access_control.rb:32:in `block in permissions_attributes='
  hydra-access-controls (10.5.0) app/models/hydra/access_control.rb:25:in `permissions_attributes='
  hydra-access-controls (10.5.0) app/models/concerns/hydra/access_controls/permissions.rb:21:in `permissions_attributes_without_uniqueness='
```

**Comment by carolyncole** [comment]
@awead is suggesting that the permission get removed and then reapplied.

**Comment by carolyncole** [comment]
Adding items to the batch edit works, but removing items does not work.
