### ISSUE TITLE
Batch Edit stuck when changing permissions

### ISSUE THREAD

**Issue by hectorcorrea** [psu-libraries/scholarsphere-3#104]
- Go to dashboard
- Select 2 files
- Click Edit Selected
- Click Permissions
- Change the permissions (e.g. from public to private)
- Click Save Changes
- The system gets stuck and the permissions are _not updated_

![screen shot 2015-04-02 at 4 14 08 pm](https://cloud.githubusercontent.com/assets/568286/6972671/5f9fa732-d953-11e4-95e9-f053edd4b25a.png)

Test case https://scm.dlt.psu.edu/issues/3726

**Comment by hectorcorrea** [comment]
This is what is reported in the logs

```
2015-04-03 14:34:26 -0400 (22938) Completed 500 Internal Server Error in 273ms
2015-04-03 14:34:26 -0400 (22938) 
NoMethodError - undefined method `permit' for nil:NilClass:
  hydra-editor (1.0.2) app/forms/hydra_editor/form.rb:57:in `sanitize_params'
  hydra-editor (1.0.2) app/forms/hydra_editor/form.rb:49:in `model_attributes'
  sufia (6.0.0) app/controllers/concerns/sufia/batch_edits_controller_behavior.rb:87:in `generic_file_params'
  sufia (6.0.0) app/controllers/concerns/sufia/batch_edits_controller_behavior.rb:50:in `update_document'
  hydra-batch-edit (1.1.1) app/controllers/concerns/hydra/batch_edit_behavior.rb:39:in `block in update'
  hydra-batch-edit (1.1.1) app/controllers/concerns/hydra/batch_edit_behavior.rb:37:in `update'
  sufia (6.0.0) app/controllers/concerns/sufia/batch_edits_controller_behavior.rb:58:in `update'
```

**Comment by hectorcorrea** [comment]
The culprit seems to be this line in Sufia: https://github.com/projecthydra/sufia/blob/master/app/controllers/concerns/sufia/batch_edits_controller_behavior.rb#L87

The code to validate the attributes only accounts for fields passed when updating the "Descriptions" tab but not the case where the user edits the "Permissions" tab.

Then editing the permissions tab there is no `params[:generic_file]` and the code blows up in Hydra Editor (https://github.com/projecthydra/hydra-editor/blob/master/app/forms/hydra_editor/form.rb#L63) since there is no `permit` method in nil.

**Comment by hectorcorrea** [comment]
The change is the check in `generic_file_params` to make sure we don't pass nil to `model_attributes`

```
    def generic_file_params
      file_params = params[:generic_file] || ActionController::Parameters.new()
      Forms::BatchEditForm.model_attributes(file_params)
    end
```
