### ISSUE TITLE
Batch Edit: Setting embargo and lease does not work

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1045]
When I got to my works listing
And I choose Multiple works 
and I click Edit Selected
And I click on the collaborators tab
And I choose embargo 
And I choose a date in the future
And I click Save Changes
Then the form should not hang forever (It should set the works to embargo)

Same scenario for lease

**Comment by carolyncole** [comment]
Verified that this was an issue in production by running an edit on stage.

**Comment by carolyncole** [comment]
Here is the stack trace from the server
```
Rendering 500 page due to exception: #<ArgumentError: Invalid visibility: "embargo"> - ["/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/hydra-access-controls-10.5.0/app/models/concerns/hydra/access_controls/visibility.rb:16:in `visibility='", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/hydra-access-controls-10.5.0/app/models/concerns/hydra/access_controls/embargoable.rb:66:in `visibility='", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-11.1.6/lib/active_fedora/attribute_assignment.rb:51:in `public_send'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-11.1.6/lib/active_fedora/attribute_assignment.rb:51:in `_assign_attribute'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-11.1.6/lib/active_fedora/attribute_assignment.rb:45:in `block in _assign_attributes'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-11.1.6/lib/active_fedora/attribute_assignment.rb:44:in `_assign_attributes'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-11.1.6/lib/active_fedora/attribute_assignment.rb:38:in `assign_attributes'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-11.1.6/lib/active_fedora/attribute_assignment.rb:9:in `attributes='", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-11.1.6/lib/active_fedora/attributes/serializers.rb:24:in `attributes='", "/opt/heracles/deploy/scholarsphere/releases/20171115235014/app/controllers/batch_edits_controller.rb:29:in `update_document'", "/opt/heracles/deploy/scholarsphere/releases/20171115235014/app/controllers/batch_edits_controller.rb:17:in `block in update'", "/opt/heracles/deploy/scholarsphere/releases/20171115235014/app/controllers/batch_edits_controller.rb:17:in `map'", "/opt/heracles/deploy/scholarsphere/releases/20171115235014/app/controllers/batch_edits_controller.rb:17:in `update'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-maintenance-2.0.1/lib/rack/maintenance.rb:19:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/conditionalget.rb:38:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-11.1.6/lib/active_fedora/ldp_cache.rb:26:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/flipflop-2.3.1/lib/flipflop/feature_cache.rb:12:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/ssl.rb:24:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:81:in `block in process_request'", "/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:367:in `maybe_tag_logger'", "/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:81:in `process_request'", "/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:145:in `accept_and_process_next_request'", "/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:98:in `main_loop'", "/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler.rb:440:in `block (3 levels) in start_threads'", "/usr/share/ruby/vendor_ruby/phusion_passenger/utils.rb:97:in `block in create_thread_and_abort_on_exception'"]
```
