### ISSUE TITLE
Upgrade to ruby 2.4 or later

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1324]
This upgrade is needed for compatibility with calmav and the Fedora operating system

It is also needed for the end of life of 2.3.3 in March 2019

2.5 would be nice

**Comment by carolyncole** [comment]
Tried to upgrade to 2.5.1, but sufia is not compatible.

**Comment by carolyncole** [comment]
Ruby 2.4.4 also gets the same error:

/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:21: warning: constant ::Fixnum is deprecated
bundler: failed to load command: rspec (/Users/cam156/.rbenv/versions/2.4.4/bin/rspec)
Bundler::GemRequireError: There was an error while trying to load the gem 'sufia'.
Gem Load Error is: wrong argument type Class (expected Module)
Backtrace for gem load error is:
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:23:in `include'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:23:in `block (2 levels) in <main>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:22:in `class_eval'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:22:in `block in <main>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:21:in `each'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:21:in `<main>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8.rb:22:in `<main>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:108:in `available?'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `each'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `find'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `best_available'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:57:in `autodetect'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<main>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/babel-transpiler-0.7.0/lib/babel/transpiler.rb:1:in `<main>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/sprockets-es6-0.9.2/lib/sprockets/es6.rb:1:in `<main>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/hydra-editor-3.1.2/lib/hydra_editor/engine.rb:4:in `<class:Engine>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/hydra-editor-3.1.2/lib/hydra_editor/engine.rb:2:in `<module:HydraEditor>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/hydra-editor-3.1.2/lib/hydra_editor/engine.rb:1:in `<main>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/hydra-editor-3.1.2/lib/hydra-editor.rb:1:in `<main>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/curation_concerns-1.7.8/lib/curation_concerns/engine.rb:3:in `<main>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/curation_concerns-1.7.8/lib/curation_concerns.rb:3:in `<main>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/hydra-batch-edit-2.1.0/lib/hydra-batch-edit.rb:1:in `<main>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/sufia-7.4.1/lib/sufia.rb:14:in `<main>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:63:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:63:in `block in require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:62:in `require_with_bootsnap_lfi'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:71:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:76:in `each'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:76:in `block in require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:65:in `each'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:65:in `require'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler.rb:114:in `require'
/Users/cam156/scholarsphere/config/application.rb:18:in `<top (required)>'
/Users/cam156/scholarsphere/config/environment.rb:4:in `require'
/Users/cam156/scholarsphere/config/environment.rb:4:in `<top (required)>'
/Users/cam156/scholarsphere/spec/rails_helper.rb:19:in `require'
/Users/cam156/scholarsphere/spec/rails_helper.rb:19:in `<top (required)>'
/Users/cam156/scholarsphere/spec/actors/curation_concerns/generic_work_actor_spec.rb:3:in `require'
/Users/cam156/scholarsphere/spec/actors/curation_concerns/generic_work_actor_spec.rb:3:in `<top (required)>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
/Users/cam156/.rbenv/versions/2.4.4/bin/rspec:23:in `load'
/Users/cam156/.rbenv/versions/2.4.4/bin/rspec:23:in `<top (required)>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `load'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:28:in `run'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli.rb:424:in `exec'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli.rb:27:in `dispatch'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/cli.rb:18:in `start'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/exe/bundle:30:in `block in <top (required)>'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/exe/bundle:22:in `<top (required)>'
/Users/cam156/.rbenv/versions/2.4.4/bin/bundle:23:in `load'
/Users/cam156/.rbenv/versions/2.4.4/bin/bundle:23:in `<main>'
Bundler Error Backtrace:

  /Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require'
  /Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
  /Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:76:in `each'
  /Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:76:in `block in require'
  /Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:65:in `each'
  /Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:65:in `require'
  /Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler.rb:114:in `require'
  /Users/cam156/scholarsphere/config/application.rb:18:in `<top (required)>'
  /Users/cam156/scholarsphere/config/environment.rb:4:in `require'
  /Users/cam156/scholarsphere/config/environment.rb:4:in `<top (required)>'
  /Users/cam156/scholarsphere/spec/rails_helper.rb:19:in `require'
  /Users/cam156/scholarsphere/spec/rails_helper.rb:19:in `<top (required)>'
  /Users/cam156/scholarsphere/spec/actors/curation_concerns/generic_work_actor_spec.rb:3:in `require'
  /Users/cam156/scholarsphere/spec/actors/curation_concerns/generic_work_actor_spec.rb:3:in `<top (required)>'
  /Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
  /Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
  /Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
  /Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
  /Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
  /Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
  /Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
  /Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/cam156/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
  /Users/cam156/.rbenv/versions/2.4.4/bin/rspec:23:in `load'
  /Users/cam156/.rbenv/versions/2.4.4/bin/rspec:23:in `<top (required)>'
