### ISSUE TITLE
Investigate Why Downloading Large collection as zip fails 

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#1328]
When attempting to download https://scholarsphere.psu.edu/collections/79407x18h this collection as a zip errors out.

```
Error
There was an error with your request

If this error continues please use the the contact form for assistance uploading your content"
```

We need to know why this is failing.  If it is related to Fedora we may want to wait to fix until the content is external to fedora.

Include options for fixing and create the ticket to fix it with the information found.

**Comment by carolyncole** [comment]
Should we look into globus??

**Comment by carolyncole** [comment]
Got an error message from the server.  Looks like there is a Work in the Collection without an original file
```
2018-08-09 11:20:08 -0400 (15993) Rendering 500 page due to exception: #<NoMethodError: undefined method `uri' for nil:NilClass> - ["/opt/heracles/deploy/scholarsphere/releases/20180619102935/app/services/work_zip_service.rb:82:in `redirect_object?'", "/opt/heracles/deploy/scholarsphere/releases/20180619102935/app/services/work_zip_service.rb:78:in `add_to_zip?'", "/opt/heracles/deploy/scholarsphere/releases/20180619102935/app/services/work_zip_service.rb:64:in `add_internal_files_to_zip'", "/opt/heracles/deploy/scholarsphere/releases/20180619102935/app/services/work_zip_service.rb:51:in `add_files_to_zip'", "/opt/heracles/deploy/scholarsphere/releases/20180619102935/app/services/work_zip_service.rb:39:in `block (2 levels) in call'", "/opt/heracles/deploy/scholarsphere/releases/20180619102935/app/services/work_zip_service.rb:38:in `each'", "/opt/heracles/deploy/scholarsphere/releases/20180619102935/app/services/work_zip_service.rb:38:in `block in call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rubyzip-1.2.1/lib/zip/file.rb:101:in `open'", "/opt/heracles/deploy/scholarsphere/releases/20180619102935/app/services/work_zip_service.rb:37:in `call'", "/opt/heracles/deploy/scholarsphere/releases/20180619102935/app/services/collection_zip_service.rb:13:in `add_files_to_zip'", "/opt/heracles/deploy/scholarsphere/releases/20180619102935/app/services/work_zip_service.rb:39:in `block (2 levels) in call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/relation/delegation.rb:16:in `each'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/relation/delegation.rb:16:in `each'", "/opt/heracles/deploy/scholarsphere/releases/20180619102935/app/services/work_zip_service.rb:38:in `block in call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rubyzip-1.2.1/lib/zip/file.rb:101:in `open'", "/opt/heracles/deploy/scholarsphere/releases/20180619102935/app/services/work_zip_service.rb:37:in `call'", "/opt/heracles/deploy/scholarsphere/releases/20180619102935/app/controllers/downloads_controller.rb:23:in `load_file'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/hydra-core-10.5.0/app/controllers/concerns/hydra/controller/download_behavior.rb:45:in `file'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/curation_concerns-1.7.8/app/controllers/concerns/curation_concerns/download_behavior.rb:16:in `show'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-maintenance-2.0.1/lib/rack/maintenance.rb:19:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/etag.rb:24:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/conditionalget.rb:25:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/head.rb:13:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/session/abstract/id.rb:225:in `context'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/session/abstract/id.rb:220:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/ldp_cache.rb:26:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/flipflop-2.3.1/lib/flipflop/feature_cache.rb:12:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/methodoverride.rb:22:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/runtime.rb:18:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.9/lib/rack/sendfile.rb:113:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/ssl.rb:24:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:81:in `block in process_request'", "/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:364:in `maybe_tag_logger'", "/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:81:in `process_request'", "/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:134:in `accept_and_process_next_request'", "/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:95:in `main_loop'", "/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler.rb:439:in `block (3 levels) in start_threads'", "/usr/share/ruby/vendor_ruby/phusion_passenger/utils.rb:97:in `block in create_thread_and_abort_on_exception'"]    
2018-08-09 11:20:35 -0400 (15993) Calling ActiveFedora::SolrService.get without passing an explicit value for ':rows' is not recommended. You will
```

**Comment by srerickson** [comment]
Is there a way to know which Work is missing the original file? I'm assuming this means I need to contact the researcher and ask them to re-upload the file.

**Comment by olendorf** [comment]
I definitely am pro-globus, but not sure how useful it is if the researcher doesn't have globus on their end. Last I worked with it, it worked on endpoints, and my server at the time was one, the repo another. It may not work so well still for researchers on their local machine (could definitely be wrong). 

Also, I think it needs to wait until we move our content to  a file system.

WE might also think FTP or something like that either in addition.

**Comment by awead** [comment]
@cam156 Has this been fixed with the issue of permissions in the Fedora/Modeshape binary store directories?

**Comment by carolyncole** [comment]
@awead  yesish.
