### ISSUE TITLE
Update index with External Content and Extracted Text Fails

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1350]
An error occurs when updating the index on a FileSet with external content and extracted text that is also external.

Convert FileSet('63x816n35p') to external then run the code below to see the error.

```
fs = FileSet.find('63x816n35p')
fs.update_index
2018-08-22 07:57:58 -0400 (22510) could not convert File Set content to UTF8 63x816n35p undefined method `force_encoding' for #<StringIO:0x0055e22051e980>                                                                                                                                          
Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8                                                                               
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:34:in `encode'                                                                                                                                       
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:34:in `to_json'                                                                                                                                      
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'                                                                                                          
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/json/encoding.rb:57:in `to_json'                                                                                                                                             
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/json-1.8.6/lib/json/common.rb:223:in `generate'                     
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/json-1.8.6/lib/json/common.rb:223:in `generate'                     
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/json/encoding.rb:101:in `stringify'                                                                                                                                          
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/json/encoding.rb:35:in `encode'                                                                                                                                              
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/json/encoding.rb:22:in `encode'                                                                                                                                              
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'                                                                                                          
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rsolr-2.1.0/lib/rsolr/json.rb:20:in `add'                           
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:103:in `add'                        
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/solr_service.rb:87:in `add'  
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/indexing.rb:43:in `update_index'                                                                                                                                               
        from (irb):94                                                                                                                             
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'       
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'         
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'                                                                                                                                                 
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'                                                                                                                                            
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<main>'               
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'                                                                                                                                
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'                                                                                                     
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'                                                                                                                                 
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'                                                                                                              
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/bootsnap-1.2.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'                                                                                                                                
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'                                                                                                                                    
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'                                                                                                                                     
        from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'                                                                                                                                             
        from script/rails:6:in `<main>'   
```

**Comment by carolyncole** [comment]
@bess tested this on DCEFedora and it is fixed
