### ISSUE TITLE
Analysis of failed migration

### ISSUE THREAD

**Issue by bess** [psu-libraries/scholarsphere-3#1386]
- [x] Provide a list of pids that failed migration on dce-fedora
- [ ] Go through each and try to figure out why

Child of #1128

**Comment by bess** [comment]
@cam156 : These are the objects that have failed migration so far:

sq87bt630
d5138jg05w
w0892b27s
7h149p912
76537140z
n296wz28h
7p88cg66f
bvq27zn031
x346f087g
8623hx82z
cj82k740x
qv33rw719
2801pg402
37720c880
4q77fr46p
sf268b28v
6w924b87t
8623hx78c
qr46r085k
2801pg41b
h128nd71m
5712mb60n
5712m701v
nv935291f
x346dv94w
cn69m429f
xw42n792v
76537145b
2801pg42m
4f4752g50f
cz30ps722
x059c736d
x346dz139
r781wg270
2801pg37r
hq37vn56b
cj82k747v
z316q162x
1j92g750d
gh93gz64m
6w924b840
7p88cg523
gx41mh91j
t148fh143
pr76f341v
5712mr21f
kk91fk580
x346dv16h
d217qp592
7d278v65m
5712mj330
tx31qh855
8910jt77b
x346dx108
4j03cz73v
x346dm99t
sf268c061
~h1831cm636 (this one causes an out of memory error)~ (fixed)
zk51vg948
kp78gg381
r494vk31b
4f4752g62b
gx41mh908
ws859f716
hd76s0057
76537142h
9s1616253
kk91fk62k
5712mg443
3n583xt387
wd375w30z
j3860692c
pv63g096p
vh53wv90n
8049g510m
79407x27g
xp68kg28j
5712mx958
x346dz63h
f7623c912
0vt150g85b
dnc580m898
rr494vm196
2018-09-04 16:35:37 -0400 (14996) error migrating object: cjs956g06f; 404 Not Found

**Comment by bess** [comment]
Some of these are in the error log because they showed up during re-migration because of this error: 
```
2018-09-01 14:31:20 -0400 (10492) error migrating object: sq87bt630; The specified label "auto_placeholder" is already assigned to another version of this resource!
```

That means they probably DID migrate correctly on a previous run, but they were one of the objects for which an `auto_placeholder` version was left in place, and when I re-run the migration (e.g., because I was trying to re-run the failed file 7) they are hitting this error.
I will make a separate ticket to address that as a special case of "Do not try to re-migrate an object that has already been migrated".

**Comment by bess** [comment]
Other errors look like this:

```
2018-08-31 21:30:00 -0400 (21744) error migrating object: x346dx108; STATUS: 500 org.modeshape.jcr.value.binary.BinaryStoreException: Unable to find binary value with key "de4783dd337995ed2f7c52d8bd738ae7cfd9b407" within binary store at "/opt/heracles/fedora/SStestFedora/binary.store"
        at org.modeshape.jcr.value.binary.FileSystemBinaryStore.getInputStream(FileSystemBinaryStore.java:319)
        at org.modeshape.jcr.value.binary.StoredBinaryValue.internalStream(StoredBinaryValue.java:70)
        at org.modeshape.jcr.value.binary.AbstractBinary.getStream(AbstractBinary.java:166)
        at org.fcrepo.kernel.modeshape.FedoraBinaryImpl.getContent(FedoraBinaryImpl.java:122)
        at org.fcrepo.http.api.ContentExposingResource.getBinaryContent(ContentExposingResource.java:350)
        at org.fcrepo.http.api.ContentExposingResource.getContent(ContentExposingResource.java:190)
        at org.fcrepo.http.api.FedoraLdp.getResource(FedoraLdp.java:248)
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.la...
```

**Comment by bess** [comment]
Log files are in /opt/heracles/deploy/scholarsphere/current/log if you want to do a grep and see why each work id failed.

**Comment by carolyncole** [comment]
Content is present in production - Version error.
sq87bt630 - docx
x346dm99t - pdf
sf268c061 - docx

Content Present in production - Net read timeout??
d5138jg05w - nex
w0892b27s - nex
7h149p912 - pl
h128nd71m - pdf
7p88cg523 - zip

Content Present - 500 Internal Server Error
76537140z - xlsx
n296wz28h - docx
7p88cg66f - zip
bvq27zn031 - rar & pdf
qv33rw719 - pdf
2801pg402 - xlsx
2801pg41b - xlsx
5712mb60n - ppt
nv935291f - csv
xw42n792v - xlsx
76537145b - xlsx
2801pg42m - xslx
cz30ps722 - xslx
x346dz139 - zip
r781wg270 - tar
2801pg37r - xslx
cj82k747v - pdf
gx41mh91j - pdf
t148fh143 - docx
pr76f341v - xslx
5712mr21f - zip
x346dv16h - ppt
5712mj330 - 7z
8910jt77b - txt
4j03cz73v - pdf

Content Present - Execution expired
x346f087g - pdf
5712m701v - pdf
gh93gz64m - sda

Content Present - Discovered tombstone
8623hx82z - pdf
cj82k740x - pdf
37720c880 - pdf
sf268b28v - pdf
6w924b87t - pdf
8623hx78c - pdf
qr46r085k - pdf
x346dv94w - pdf
cn69m429f - pdf
4f4752g50f - pdf
x059c736d - pdf
hq37vn56b - pdf
z316q162x - pdf
1j92g750d - xslx
6w924b840 - pdf
kk91fk580 - pdf
d217qp592 - pdf
7d278v65m - ppt

Content Present - Unable to find binary value with key
4q77fr46p - pdf
tx31qh855 - pdf
x346dx108 - pdf
zk51vg948 - pdf

Out of Memory
h1831cm636 (this one causes an out of memory error)

**Comment by bess** [comment]
@cam156 I'm going to re-run all our error objects w/ latest code and then provide you any that are still erroring
