### ISSUE TITLE
Tests are contacting LDAP.

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#148]
I think we should stop our tests from contacting LDAP. We are getting intermittent failures.

  6) unified search {:type=>:feature} all files known user searches all
     Failure/Error: expect(page).to have_content("All")
       expected to find text "All" in "RuntimeError in HomepageController#index retry_unless could not complete successfully. Try upping the # of tries? Extracted source (around line #19): 17 18 19 20 21 22 sleep(ScholarSphere::Application.config.ldap_unwilling_sleep) end raise RuntimeError, \"retry_unless could not complete successfully. Try upping the # of tries?\" end end end Rails.root: /Users/cam156/scholarsphere Application Trace | Framework Trace | Full Trace lib/scholarsphere/utils.rb:19:in `retry_unless' app/models/user.rb:121:in`groups' app/models/user.rb:103:in `groups!' app/models/user.rb:96:in`groups' Request Parameters: None Toggle session dump Toggle env dump Response Headers: None"
     # ./spec/features/unified_search_spec.rb:56:in `block (4 levels) in <top (required)>'

**Comment by mjgiarlo** [comment]
:+1: though it may be worth leaving one test that hits LDAP so that we can be sure that works as expected.
