### ISSUE TITLE
arkivo api & share api are overlapping

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#218]
When the share api is defined for some reason rails has trouble loading the api in the controller area from sufia (https://github.com/projecthydra/sufia/tree/master/app/controllers/api).

If you delete that file the items controller work fine.  There seems to be a conflict between the two api definitions and the rails classloader.

2015-12-17 07:29:23 -0500 (64662) Started POST "/api/items" for 127.0.0.1 at 2015-12-17 07:29:23 -0500
2015-12-17 07:29:23 -0500 (64662) Value for params[:metadata][:tags] was set to nil, because it was one of [], [null] or [null, null, ...]. Go to http://guides.rubyonrails.org/security.html#unsafe-query-generation for more information.
2015-12-17 07:29:23 -0500 (64662) 
LoadError - Unable to autoload constant API, expected /Users/cam156/scholarsphere/lib/share_notify/api.rb to define it:
  activesupport (4.2.2) lib/active_support/dependencies.rb:495:in `load_missing_constant'
  activesupport (4.2.2) lib/active_support/dependencies.rb:184:in`const_missing'
  activesupport (4.2.2) lib/active_support/inflector/methods.rb:261:in `block in constantize'
  activesupport (4.2.2) lib/active_support/inflector/methods.rb:259:in`constantize'
  activesupport (4.2.2) lib/active_support/dependencies.rb:566:in `get'
  activesupport (4.2.2) lib/active_support/dependencies.rb:597:in`constantize'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:70:in `controller_reference'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:60:in`controller'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:39:in `serve'
  actionpack (4.2.2) lib/action_dispatch/routing/mapper.rb:49:in`serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in`serve'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:819:in `call'
  railties (4.2.2) lib/rails/engine.rb:518:in`call'
  railties (4.2.2) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.2) lib/action_dispatch/routing/mapper.rb:51:in`serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in`serve'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:819:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in`call'
  newrelic_rpm (3.14.0.305) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in`call'
  newrelic_rpm (3.14.0.305) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in`call'
  rack-maintenance (2.0.1) lib/rack/maintenance.rb:19:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in`call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in`call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in`call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in`call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in`call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/params_parser.rb:27:in`call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/flash.rb:260:in`call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in`context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in`call'
  actionpack (4.2.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in`call'
  activerecord (4.2.2) lib/active_record/query_cache.rb:36:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in`call'
  activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in`call'
  active-fedora (9.5.0) lib/active_fedora/ldp_cache.rb:26:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in`call'
  actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:88:in`_run_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in`call'
  actionpack (4.2.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in`call'
  actionpack (4.2.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in`call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in`better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in`call'
  actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in`call'
  actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in`call'
  railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.2) lib/rails/rack/logger.rb:20:in`block in call'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in`tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.2) lib/rails/rack/logger.rb:20:in`call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in`call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in`call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in`call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in`call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in`call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/static.rb:113:in`call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in`call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  railties (4.2.2) lib/rails/engine.rb:518:in`call'
  railties (4.2.2) lib/rails/application.rb:164:in `call'
  railties (4.2.2) lib/rails/railtie.rb:194:in`method_missing'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in`call'
  unicorn (5.0.0) lib/unicorn/http_server.rb:562:in `process_client'
  unicorn (5.0.0) lib/unicorn/http_server.rb:658:in`worker_loop'
  unicorn (5.0.0) lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
  unicorn (5.0.0) lib/unicorn/http_server.rb:132:in`start'
  unicorn-rails (2.2.0) lib/unicorn_rails.rb:33:in `run'
  rack (1.6.4) lib/rack/server.rb:286:in`start'
  railties (4.2.2) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.2) lib/rails/commands/commands_tasks.rb:80:in`block in server'
  railties (4.2.2) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.2) lib/rails/commands/commands_tasks.rb:39:in`run_command!'
  railties (4.2.2) lib/rails/commands.rb:17:in `<top (required)>'
  railties (4.2.2) lib/rails/app_rails_loader.rb:45:in`block in exec_app_rails'
  railties (4.2.2) lib/rails/app_rails_loader.rb:34:in `exec_app_rails'
  railties (4.2.2) lib/rails/cli.rb:5:in`<top (required)>'
  railties (4.2.2) bin/rails:9:in `<top (required)>'
  /Users/cam156/.rbenv/versions/2.2.3/bin/rails:23:in`<main>'

**Comment by carolyncole** [comment]
Seems to be fixed with the new share gem
