### ISSUE TITLE
poltergeist 1.8.x breaks some tests

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#240]
We're getting these test failures with potergeist 1.8.1:

``` bash
1) Batch management of generic files Editing multiple files Viewing the batch edit form Fills in each field from the database
     Failure/Error: expect(page).to have_css("div##{div_id}")

     Capybara::Poltergeist::InvalidSelector:
       The browser raised a syntax error while trying to evaluate css selector "div#http://127.0.0.1:59978/batch_edits/edit?batch_document_ids%5B%5D=m039k4971&batch_document_ids%5B%5D=j3860696gcollapse_contributor"
     # /Users/awead/.gem/ruby/2.2.3/gems/poltergeist-1.8.1/lib/capybara/poltergeist/browser.rb:347:in `command'
     # /Users/awead/.gem/ruby/2.2.3/gems/poltergeist-1.8.1/lib/capybara/poltergeist/browser.rb:62:in `find'
     # /Users/awead/.gem/ruby/2.2.3/gems/poltergeist-1.8.1/lib/capybara/poltergeist/driver.rb:120:in `find'
     # /Users/awead/.gem/ruby/2.2.3/gems/poltergeist-1.8.1/lib/capybara/poltergeist/driver.rb:128:in `find_css'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/node/base.rb:102:in `find_css'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/query.rb:108:in `block in resolve_for'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/node/base.rb:80:in `synchronize'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/query.rb:106:in `resolve_for'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/node/matchers.rb:94:in `block in assert_selector'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/node/base.rb:84:in `synchronize'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/node/matchers.rb:93:in `assert_selector'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/session.rb:698:in `block (2 levels) in <class:Session>'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/rspec/matchers.rb:23:in `matches?'
     # ./spec/features/batch_edit_spec.rb:155:in `expand'
     # ./spec/features/batch_edit_spec.rb:88:in `block (4 levels) in <top (required)>'


  2) Generic File uploading and deletion: When logged in as a PSU user user needs help I can view help for rights, visibility, and share with
     Failure/Error: attach_file 'files[]', test_file_path(filename)

     Capybara::ElementNotFound:
       Unable to find file field "files[]"
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/node/finders.rb:43:in `block in find'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/node/base.rb:84:in `synchronize'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/node/finders.rb:32:in `find'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/node/actions.rb:157:in `attach_file'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/session.rb:698:in `block (2 levels) in <class:Session>'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/generic_file/upload_and_delete_spec.rb:31:in `block (4 levels) in <top (required)>'


  3) Generic File uploading and deletion: When logged in as a PSU user user does not need help with a single file uploading, deleting and notifications
     Failure/Error: attach_file 'files[]', test_file_path(filename)

     Capybara::ElementNotFound:
       Unable to find file field "files[]"
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/node/finders.rb:43:in `block in find'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/node/base.rb:84:in `synchronize'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/node/finders.rb:32:in `find'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/node/actions.rb:157:in `attach_file'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/session.rb:698:in `block (2 levels) in <class:Session>'
     # /Users/awead/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/support/helpers/generic_files.rb:11:in `upload_generic_file'
     # ./spec/features/generic_file/upload_and_delete_spec.rb:156:in `block (5 levels) in <top (required)>'
```

**Comment by awead** [comment]
Fixed in #254
