### ISSUE TITLE
Migrate_audit_spec fails 

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#270]
When I run all the test the migrate_audit_test constantly fails.
When I run the tests individually is consistently passes,

I'm guessing this has something to do with the fact that we are not cleaning up before or after each test.

Here are the errors:

  1) MigrateAudit with a file migrated correctly returns OK
     Failure/Error: expect(subject.status).to eq("OK")

```
   expected: "OK"
        got: "Not found"

   (compared using ==)
 # ./spec/models/migrate_audit_spec.rb:31:in `block (3 levels) in <top (required)>'
```

  2) MigrateAudit with a file migrated incorrectly reports models mismatch
     Failure/Error: expect(subject.status).to eq("Models mismatch. Expected: GenericFileFake but found: GenericFile")

```
   expected: "Models mismatch. Expected: GenericFileFake but found: GenericFile"
        got: "Not found"

   (compared using ==)
 # ./spec/models/migrate_audit_spec.rb:48:in `block (3 levels) in <top (required)>'
```

**Comment by awead** [comment]
I'm not seeing these. Which branch are you on?

**Comment by carolyncole** [comment]
@awead I have been seeing them for the past month (and forgot to ticket it), but I am specifically on ldap_gem right now...  On the bright side travis is not seeing the issue, but it is possible it will creep in there too, so I wanted to make a note...

**Comment by awead** [comment]
I'm not seeing it locally. Have you tried rebasing off of develop?

**Comment by awead** [comment]
@cam156 Ok, now I'm seeing it! If you run the whole suite locally, you get the error, but as you said, not in Travis, which is weird. You can try forcing a cleanup before the test with `it "blah", clean: true do`
