### ISSUE TITLE
Unable to create new resources in QA

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#502]
When attempting to create new works in QA, Solr returns this error:

```
2016-12-16 10:46:25 -0500 (25036) Rendering 500 page due to exception: #<RSolr::Error::Http: RSolr::Error::Http - 500 Internal Server Error
Error: 'Exception writing document id 09f6d199-7e93-424d-847f-a90b43e57931 to the index; possible analysis error.','trace'=>'org.apache.solr.common.
SolrException: Exception writing document id 09f6d199-7e93-424d-847f-a90b43e57931 to the index; possible analysis error.

URI: http://ssrepo1qa:8080/SSqaSolr4F4/collection1/update?wt=ruby&softCommit=true
Request Headers: {"Content-Type"=>"text/xml"}
Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><add><doc><field name=\"system_create_dtsi\">2016-12-16T15:46:25Z</field><field name=\"syst
em_modified_dtsi\">2016-12-16T15:46:25Z</field><field name=\"has_model_ssim\">Hydra::AccessControl</field><field name=\"id\">09f6d199-7e93-424d-847f-a90b43e57931</field><field name=\"object_profile_ssm\">{\"id\":\"09f6d199-7e93-424d-847f-a90b43e57931\"}</field></doc></add>"

Backtrace: /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:288:in `adapt_response'
/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:189:in `execute'
/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:175:in `send_and_receive'
(eval):2:in `post'
/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:84:in `update'
/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:104:in `add'
/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/solr_service.rb:69:in `add'
/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/indexing.rb:43:in `update_index'
/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/indexing.rb:65:in `_create_record'
/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/callbacks.rb:240:in `block in _create_record'
```

**Comment by awead** [comment]
See also: #503

**Comment by awead** [comment]
Restarting tomcat fixed the issue, however, the ACL issue remains.
