### ISSUE TITLE
undefined method `add_foreign_key'

### ISSUE THREAD

**Issue by jcoyne** [psu-libraries/scholarsphere-3#60]
```
rake aborted!
NoMethodError: undefined method `add_foreign_key' for #<ActiveRecord::Schema:0x007f9688f7f9b0>
/Users/justin/workspace/scholarsphere/db/schema.rb:304:in `block in <top (required)>'
/Users/justin/workspace/scholarsphere/db/schema.rb:14:in `<top (required)>'
Tasks: TOP => db:schema:load
```

**Comment by jcoyne** [comment]
If I do "rake db:migrate" it makes a different db/schema.rb with this at the end:

```
-  add_foreign_key "mailboxer_conversation_opt_outs", "mailboxer_conversations", name: "mb_opt_outs_on_conversations_id", column: "conversation_id"
-
-  add_foreign_key "mailboxer_notifications", "mailboxer_conversations", name: "notifications_on_conversation_id_development", column: "conversation_id"
-
-  add_foreign_key "mailboxer_receipts", "mailboxer_notifications", name: "mailboxer_receipts_on_notification_id_development", column: "notification_id"
-
+  Foreigner.load
```

Should I commit that?

**Comment by jcoyne** [comment]
This may be because I'm running sqlite and you are running mysql maybe?

**Comment by jcoyne** [comment]
@awead do you have any details on this resolution? Is this just stale?

**Comment by awead** [comment]
@jcoyne yeah, it's like the schema.rb was committed at some point, otherwise, we haven't seen this error.
