### ISSUE TITLE
Characters in the description can cause the work upload to 500 error

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#608]
When I put any characters in the description of a work
Then the work should be generated correctly

To reproduce the problem create a work with the following description:

```
The ignitibility behaviour of eleven coals ranging in rank trom low volatile bituminous to high volatile C bituminous has been examined by means of two laboratory tests. The ignition temperatures of dusts ranging in size from -6o+200 to -325 mesh (U. S. Sieve a.,_ries) were determined in oxygen and in air using the Godbert inflammability apparatus, in which 0.2 gram of coal was blown downwards through a heated, vertical ignition tube using 2000 cc. of gas at a pressure of 1211 mercury. The crossing-point temperatures in oxygen of 3.0 grBJI sampies of the -6o+200 mesh coals were obtained with a Setchk.in 'tg~ n1tion Apparatus :f.or solids. In this test the temperature/time his'4:\ tory of a coal was compared with that of the preheated oxygen with which it reacted under the standard conditions of the test. The crossing-point temperature was that at which the temperature/time curves of coal and 01tygen intersected. No correlation ,between the volatile content of the coals and either their ignition point temperatures in air or oxygen, or their crossing point temperatures in o~ygEtn, was found. Results with the inflammability apparatus showed, however, a definite decrease in ignition temperature with decrease in particle size. The following conclusions were drawn from the study: (1) The ~gnitibility of a bituminous coal is determined not by its total volatile content, but rather by the surface properties .of both the original and partially charred or carbonised particles. (2) Differences in the ignitibility of the bituminous class of coals are less marked than has sometimes been supposed; provided that sufficient oxygen is available, bituminous coals over a wide range of volatile contents will ignite at much the same ain.bient temperature wheh projected into a suitable hot environment in the size consist used for pulverised fuel firing, (3) The ignitibility of a cloud of coal dust particles increase~ as the particle size decreases. Particle size is more important in the ignition process than is the:i:rifluence of volatile content. 
```

That creates an RDF was not parsable error.  I am guessing there are characters in the above description that need to be escaped for RDF.

```
017-02-03 08:04:32 -0500 (6612) Rendering 500 page due to exception: #<Ldp::BadRequest: RDF was not parsable: [line: 16, col (0x0D)> - ["/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/ldp-0.5.0/lib/ldp/client/methods.rb:119:in `block in check_for_errors'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/ldp-0.5.0/lib/ldp/client/methods.rb:117:in `tap'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/ldp-0.5.0/lib/ldp/client/methods.rb:117:in `check_for_errors'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/ldp-0.5.0/lib/ldp/client/methods.rb:96:in `block in put'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/ldp-0.5.0/lib/ldp/client/methods.rb:88:in `put'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/caching_connection.rb:24:in `put'", "/opt/heracles/deploy/.rbenv/versions/2.3.3/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/initializing_connection.rb:42:in `put'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/ldp-0.5.0/lib/ldp/resource.rb:83:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/ldp-0.5.0/lib/ldp/resource/rdf_source.rb:21:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/persistence.rb:167:in `_create_record'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/indexing.rb:64:in `_create_record'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/callbacks.rb:240:in `block in _create_record'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/callbacks.rb:240:in `_create_record'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/persistence.rb:159:in `create_or_update'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/callbacks.rb:236:in `block in create_or_update'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/callbacks.rb:236:in `create_or_update'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/persistence.rb:29:in `save'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/validations.rb:50:in `save'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/associations/builder/orders.rb:41:in `save'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/base_actor.rb:50:in `save'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/base_actor.rb:15:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/actor_stack.rb:22:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/interpret_visibility_actor.rb:73:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/actor_stack.rb:22:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/abstract_actor.rb:25:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/actor_stack.rb:22:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/attach_files_actor.rb:7:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/actor_stack.rb:22:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/assign_representative_actor.rb:5:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/actor_stack.rb:22:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/add_to_work_actor.rb:6:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/actor_stack.rb:22:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/add_to_collection_actor.rb:6:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/actor_stack.rb:22:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/sufia-603e8fc8bd4f/app/actors/sufia/create_with_files_actor.rb:6:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/actor_stack.rb:22:in `create'", "/opt/heracles/deploy/scholarsphere/releases/20170130164732/app/actors/sufia/create_with_remote_files_actor.rb:8:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/actors/curation_concerns/actors/actor_stack.rb:22:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/curation_concerns-b073550c40a1/app/controllers/concerns/curation_concerns/curation_concern_controller.rb:38:in `create'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:298:in `block in halting_and_conditional'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:497:in `block in around'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-maintenance-2.0.1/lib/rack/maintenance.rb:19:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/etag.rb:24:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/conditionalget.rb:38:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/active-fedora-10.3.0/lib/active_fedora/ldp_cache.rb:26:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/flipflop-0eecddade989/lib/flipflop/feature_cache.rb:12:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/ssl.rb:24:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'", "/usr/lib/ruby/1.8/phusion_passenger/rack/thread_handler_extension.rb:81:in `block in process_request'", "/usr/lib/ruby/1.8/phusion_passenger/rack/thread_handler_extension.rb:367:in `maybe_tag_logger'", "/usr/lib/ruby/1.8/phusion_passenger/rack/thread_handler_extension.rb:81:in `process_request'", "/usr/lib/ruby/1.8/phusion_passenger/request_handler/thread_handler.rb:145:in `accept_and_process_next_request'", "/usr/lib/ruby/1.8/phusion_passenger/request_handler/thread_handler.rb:98:in `main_loop'", "/usr/lib/ruby/1.8/phusion_passenger/request_handler.rb:440:in `block (3 levels) in start_threads'", "/usr/lib/ruby/1.8/phusion_passenger/utils.rb:97:in `block in create_thread_and_abort_on_exception'"]
```

**Comment by carolyncole** [comment]
Here is the place to copy an paste from the summary to get the error https://scholarsphere.psu.edu/downloads/7p88cg655.  Github has cleansed the data and if you copy and paste from the ticket.

There are possibly invisible characters or similar to what we want.  Possibly convert it to a standard and back.  The code is in the fedora-migrate gem https://github.com/projecthydra-labs/fedora-migrate/blob/master/lib/fedora_migrate/rdf_datastream_mover.rb#L31.

We should do this on all the text parameters from the form before running update_attributes.

We want this for work & collection both new and editor & file set edit.

**Comment by awead** [comment]
@cam156 I can't reproduce the failure when copying the text from the original PDF either locally or on QA. Perhaps it's fixed itself or this is a machine/browser specific thing?

**Comment by awead** [comment]
Seems to be fixed now. Neither of us can reproduce it!

**Comment by carolyncole** [comment]
Closing issue.  It can be reopened if needed later.
