### ISSUE TITLE
Characterization Job fails

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#89]
File characterization no longer runs.  All we get is an error saying the item can not be found without the pid

PEG-015-007.local:33374 on CHARACTERIZE at just now Retry or Remove
Class
 Sufia::Resque::MarshaledJob
Arguments
--- |
  BAhvOhRDaGFyYWN0ZXJpemVKb2IGOghAaWRJIg5yYjY4em01MTYGOgZFVA==
Exception
ArgumentError
Error
Couldn't find ActiveFedora::Base without an ID
/Users/cam156/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-fedora-9.0.4/lib/active_fedora/relation/finder_methods.rb:217:in `find_with_ids'
/Users/cam156/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-fedora-9.0.4/lib/active_fedora/relation/finder_methods.rb:60:in`find'
/Users/cam156/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-fedora-9.0.4/lib/active_fedora/querying.rb:3:in `find'
/Users/cam156/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/sufia-d50d19e3002d/sufia-models/app/jobs/active_fedora_pid_based_job.rb:13:in`object'
/Users/cam156/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/sufia-d50d19e3002d/sufia-models/app/jobs/characterize_job.rb:7:in `run'
/Users/cam156/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/sufia-d50d19e3002d/sufia-models/lib/sufia/models/resque.rb:32:in`perform'

**Comment by carolyncole** [comment]
This was just an artifact of my resque jobs not closing out.  Old resque jobs can not process the new code.  We need to make certain the resque jobs are set up on the servers after cap deploy.
